# Use the official Python image
FROM python:3.12-slim

# Set the working directory
WORKDIR /app

# Copy only the necessary files for FastAPI
COPY pyproject.toml poetry.lock ./
RUN pip install fastAPI
RUN pip install "uvicorn[standard]"
RUN pip install pika

COPY FastAPI /app/FastAPI

# Expose the necessary ports
EXPOSE 8000

# Command to run FastAPI
CMD ["sh", "-c", "uvicorn FastAPI.Sender:app --host 0.0.0.0 --port 8000"]
