version: '3'

services:
  rabbitmq:
    image: "rabbitmq:3.8-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbit_mqdata:/var/lib/rabbitmq

  fastapi:
    build: FastAPI
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
    environment:
      - AMQP_URL=amqp://rabbitmq?connection_attempts=10&retry_delay=10
    volumes:
      - ./FastAPI:/app/FastAPI

  receiver:
    build: Calculator
    depends_on:
      - rabbitmq
    environment:
      - AMQP_URL=amqp://rabbitmq?connection_attempts=10&retry_delay=10
    volumes:
      - ./Calculator:/app/Calculator

volumes:
  rabbit_mqdata:
    driver: local
