name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Azure Container Registry
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login -u "${{ secrets.ACR_USERNAME }}" --password-stdin externalacraction.azurecr.io

      - name: Build and push Docker images
        run: |
          for dir in */; do
            if [ -f "$dir/Dockerfile" ]; then
              # Generate a version based on date and time
              version=$(date +"%d.%m.%y-%H_%M_%S")
              # Generate the image name with version
              image_name="externalacraction.azurecr.io/${dir%/}"
              # Convert image_name to lowercase
              image_name_lower=$(echo "$image_name" | tr '[:upper:]' '[:lower:]')
              image_versioned="${image_name_lower}:${version}"
              # Debug - List contents of the current directory
              ls -l "$dir"
              # Build the Docker image using Buildx and tag it with the dynamic version
              docker buildx build -t "$image_versioned" "$dir" --load
              # Push the Docker image to the Azure Container Registry
              docker push "$image_versioned"
              
              # Tag the image as "latest" and push it
              docker tag "$image_versioned" "$image_name_lower:latest"
              docker push "$image_name_lower:latest"
            fi
          done
          
      - name: Logout from Azure Container Registry
        run: docker logout externalacraction.azurecr.io
