name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      ACR_NAME: your-acr-name
      IMAGE_NAME: your-image-name
      TAG: latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_NAME }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and push Docker image using docker-compose
      run: |
        docker-compose build
        docker-compose push
      # This step uses docker-compose to build and push the images defined in your docker-compose.yml.
