name: Docker Build and Push

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      VERSION: 0.1  # Initial version

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Step 3: Login to Azure Container Registry
      - name: Login to Azure Container Registry
        run: echo "${{ secrets.ACR_PASSWORD }}" | docker login -u "${{ secrets.ACR_USERNAME }}" --password-stdin externalacraction.azurecr.io

      # Step 4: Build and push Docker images for each directory
      - name: Build and push Docker images
        run: |
          for dir in */; do
            if [ -f "$dir/Dockerfile" ]; then
              # Increment the version
              export VERSION=$(awk -F'.' '{printf "%d.%d", $1, $2 + 1}' <<< "$VERSION")
              image_name="externalacraction.azurecr.io/${dir%/}:${VERSION}"
              image_name_lower=$(echo "$image_name" | tr '[:upper:]' '[:lower:]')
              ls -l "$dir"
              docker buildx build -t "$image_name_lower" "$dir" --load
              docker push "$image_name_lower"
            fi
          done

      # Step 5: Logout from Azure Container Registry
      - name: Logout from Azure Container Registry
        run: docker logout externalacraction.azurecr.io
