name: Pull and Deploy Images

on:
  push:
    branches:
      - master

jobs:
  deploy-images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: actions/setup-docker@v2

    - name: Log in to Azure Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AZURE_SERVER_IP }}
        username: ${{ secrets.AZURE_SERVER_USERNAME }}
        key: ${{ secrets.AZURE_PRIVATE_KEY }}
        port: 22

    - name: Log in to Azure Container Registry
      run: |
        docker login acr-name.azurecr.io -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}

    - name: Pull Docker Images
      run: |
        for dir in */; do
          if [ -f "$dir/Dockerfile" ]; then
            # Generate the image name with version
            image_name="acr-name.azurecr.io/${dir%/}"
            # Convert image_name to lowercase
            image_name_lower=$(echo "$image_name" | tr '[:upper:]' '[:lower:]')
            image_versioned="${image_name_lower}:latest"
            
            # Pull the Docker image
            docker pull $image_versioned
          fi
        done
