name: Test SSH Connection

on:
  push:
    branches:
      - master

jobs:
  test-ssh-connection:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Test SSH connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AZURE_SERVER_IP }}
        username: ${{ secrets.AZURE_SERVER_USERNAME }}
        key: ${{ secrets.AZURE_PRIVATE_KEY }}
        port: 22
        script: |
          docker images
