name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.12

    - name: Start RabbitMQ server
      run: |
        docker-compose up -d
      # This ensures that the RabbitMQ server is started before proceeding to the next steps
      continue-on-error: true

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install

    - name: Run tests
      run: poetry run pytest

    - name: Stop RabbitMQ server
      run: |
        docker-compose down
